""" Endpoints for E2E testing.  These will need to be overridden for your environment to use e2e tests"""
OTEL_USERNAME = "670195"
OTEL_ENDPOINT = "https://otlp-gateway-prod-us-east-0.grafana.net/otlp"
OTEL_TOKEN = "<insert_token_here>"
LOKI_ENDPOINT ="https://loki.capricorn.brendonmccool.com/loki/api/v1/push"
